require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# ../node_modules/react-native-macos/scripts/cocoapods/codegen_utils.rb#L87-L90
platform :macos, '10.15'
# 이 함수는 프레임워크에 노출된 모든 타깃을 처리하기 전에 프로젝트를 준비합니다.
# `install! 'cocoapods', :deterministic_uuids => false`: 중복된 GUID 오류를 억제하기 위함.
# `ReactNativePodsUtils.create_xcode_env_if_missing`: ios/xcode.env 파일이 없을 경우 생성
# 포드 설치 외부에서 파일을 생성하도록 이동하면 제거할 수 있습니다.
# ../node_modules/react-native-macos/scripts/react_native_pods.rb#L35
prepare_react_native_project!

# ../node_modules/react-native/scripts/cocoapods/utils.rb#L19
target 'HappyCar-macOS' do
  # 현재 대상의 플랫폼을 지원하지 않는 파드를 건너뜁니다.
  # current_target_definition.platform
  # Note: 지원되는 `platform`을 정의하기 전에 `use_native_modules!`를 호출할 수 없습니다.
  # ../node_modules/@react-native-community/cli-platform-ios/native_modules.rb#L15
  config = use_native_modules!

  # 'RCT_NEW_ARCH_ENABLED 및 USE_HERMES 환경변수 설정 값에 따라 변경되는 플래그입니다.
  # ../node_modules/react-native-macos/scripts/react_native_pods.rb#L186
  flags = get_default_flags()

  # ../node_modules/react-native-macos/scripts/react_native_pods.rb#L55
  use_react_native!(
    :path => '../node_modules/react-native-macos',
    # 헤르메스 컴파일러는 macOS와 기본적으로 호환되지 않습니다.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # 플리퍼는 macOS와 호환되지 않습니다.
    :flipper_configuration => FlipperConfiguration.disabled,
    # 애플리케이션 루트에 대한 절대 경로입니다.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # # 일부 플래그와 빌드 설정을 구성하기 위해 React Native를 설치한 후 실행하는 함수입니다.
    # ../node_modules/react-native-macos/scripts/react_native_pods.rb#L206
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
